### ISSUE TITLE
failed to connect to monoprice mini v2

### ISSUE THREAD

**Issue by dirkschut** [OctoPrint/OctoPrint-MalyanConnectionFix#9]
Hey there. I'm trying to connect to my monoprice select v2 printer using octoprint and it keeps failing to detect the printer. Using your plugin, this is the log octoprint gives me.

It claims that the device is busy, which is weird. But at least with your plugin I get something, while without it it just cycles through all the baud rates and says it can't find anything.

Is this something you can help me with?

```
octo-octoprint-1  | 2022-08-05 14:44:43,342 - octoprint.util.comm - ERROR - Unexpected error while connecting to serial port /dev/ttyACM0, baudrate 9600 from hook malyan_connection_fix: SerialException: '[Errno 16] could not open port /dev/ttyACM0: [Errno 16] Device or resource busy: '/dev/ttyACM0'' @ comm.py:_open_serial:3832
octo-octoprint-1  | Traceback (most recent call last):
octo-octoprint-1  |   File "/usr/local/lib/python3.8/site-packages/serial/serialposix.py", line 322, in open
octo-octoprint-1  |     self.fd = os.open(self.portstr, os.O_RDWR | os.O_NOCTTY | os.O_NONBLOCK)
octo-octoprint-1  | OSError: [Errno 16] Device or resource busy: '/dev/ttyACM0'
octo-octoprint-1  |
octo-octoprint-1  | During handling of the above exception, another exception occurred:
octo-octoprint-1  |
octo-octoprint-1  | Traceback (most recent call last):
octo-octoprint-1  |   File "/usr/local/lib/python3.8/site-packages/octoprint/util/comm.py", line 3832, in _open_serial
octo-octoprint-1  |     serial_obj = factory(
octo-octoprint-1  |   File "/usr/local/lib/python3.8/site-packages/octoprint/util/__init__.py", line 1688, in wrapper
octo-octoprint-1  |     return f(*args, **kwargs)
octo-octoprint-1  |   File "/octoprint/plugins/lib/python3.8/site-packages/octoprint_malyan_connection_fix/__init__.py", line 56, in serial_factory
octo-octoprint-1  |     serial_obj1 = serial.Serial(str(port), baudrate, timeout=read_timeout, writeTimeout=10000,
octo-octoprint-1  |   File "/usr/local/lib/python3.8/site-packages/serial/serialutil.py", line 244, in __init__
octo-octoprint-1  |     self.open()
octo-octoprint-1  |   File "/usr/local/lib/python3.8/site-packages/serial/serialposix.py", line 325, in open
octo-octoprint-1  |     raise SerialException(msg.errno, "could not open port {}: {}".format(self._port, msg))
octo-octoprint-1  | serial.serialutil.SerialException: [Errno 16] could not open port /dev/ttyACM0: [Errno 16] Device or resource busy: '/dev/ttyACM0'
octo-octoprint-1  | 2022-08-05 14:44:43,342 - octoprint.util.comm - INFO - Serial detection: Could not open port /dev/ttyACM0, baudrate 9600, skipping
octo-octoprint-1  | 2022-08-05 14:44:43,342 - octoprint.util.comm - INFO - Changing monitoring state from "Detecting serial connection" to "Error"
octo-octoprint-1  | 2022-08-05 14:44:43,344 - octoprint.util.comm - INFO - Changing monitoring state from "Error" to "Offline after error"
octo-octoprint-1  | 2022-08-05 14:44:43,364 - octoprint.plugins.action_command_notification - INFO - Notifications cleared
octo-octoprint-1  | 2022-08-05 14:44:43,959 - octoprint.plugins.tracking - INFO - Sent tracking event commerror_autodetect, payload: {'commerror_text': 'No more candidates to test, and no working port/baudrate combination detected.'}
```

**Comment by foosel** [comment]
Sorry, no idea, and no access to such a printer either. This is better suited for the [forums](https://community.octoprint.org) or the [Discord](https://discord.octoprint.org).
